site: News From Inner Space

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  travels:
    output: true
    permalink: /travel/:slug
  arts:
    output: true
    permalink: /art/:slug
  writings:
    output: true
    permalink: /writing/:slug
  historys:
    output: true
    permalink: /history/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -    
    scope:
      path: ""
      type: "travels"
    values:
      layout: "project"
  -    
    scope:
      path: ""
      type: "arts"
    values:
      layout: "project"
  -     
    scope:
      path: ""
      type: "writings"
    values:
      layout: "project"
   -     
    scope:
      path: ""
      type: "historys"
    values:
      layout: "project" 

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

#Facebook Sharing
facebook_app_id: 238963320522156
  